name: 👷　CI
on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️　Checkout
        uses: actions/checkout@v3

      - name: 🎉　Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: 🎉　Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: 🌱　Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: 🚸　Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 🚧　Install dependencies
        run: pnpm install --no-frozen-lockfile --ignore-scripts

      - name: 📦　Build
        run: pnpm run build

      - name: ✅　Test
        run: pnpm run test

      - name: configure npm
        run: |
          npm config set //repositories.mrf.io/nexus/repository/npm-internal/:_authToken ${NPM_NEXUS_AUTH} ${{ secrets.NPM_NEXUS_AUTH }}
          npm config set strict-ssl false

      - run: npm publish
